---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: composer-lock
  name: composer-lock

spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: composer-lock
